/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ParameterReading = IDL.Record({
  'historicalTrend' : IDL.Vec(IDL.Float64),
  'unit' : IDL.Text,
  'currentValue' : IDL.Float64,
});
export const Coordinates = IDL.Tuple(IDL.Float64, IDL.Float64);
export const StationData = IDL.Record({
  'pH' : ParameterReading,
  'turbidity' : ParameterReading,
  'temperature' : ParameterReading,
  'name' : IDL.Text,
  'locationDescription' : IDL.Text,
  'ecoli' : ParameterReading,
  'flowRate' : ParameterReading,
  'nitrates' : ParameterReading,
  'dissolvedOxygen' : ParameterReading,
  'macroinvertebrateIndex' : ParameterReading,
  'coordinates' : Coordinates,
});

export const idlService = IDL.Service({
  'getAllStations' : IDL.Func([], [IDL.Vec(StationData)], ['query']),
  'getStationReadings' : IDL.Func([IDL.Text], [StationData], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ParameterReading = IDL.Record({
    'historicalTrend' : IDL.Vec(IDL.Float64),
    'unit' : IDL.Text,
    'currentValue' : IDL.Float64,
  });
  const Coordinates = IDL.Tuple(IDL.Float64, IDL.Float64);
  const StationData = IDL.Record({
    'pH' : ParameterReading,
    'turbidity' : ParameterReading,
    'temperature' : ParameterReading,
    'name' : IDL.Text,
    'locationDescription' : IDL.Text,
    'ecoli' : ParameterReading,
    'flowRate' : ParameterReading,
    'nitrates' : ParameterReading,
    'dissolvedOxygen' : ParameterReading,
    'macroinvertebrateIndex' : ParameterReading,
    'coordinates' : Coordinates,
  });
  
  return IDL.Service({
    'getAllStations' : IDL.Func([], [IDL.Vec(StationData)], ['query']),
    'getStationReadings' : IDL.Func([IDL.Text], [StationData], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };